# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra_app_gen}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonathan Tron", "Joseph Halter"]
  s.date = %q{2010-03-03}
  s.default_executable = %q{sinatra_app}
  s.description = %q{Our default app template}
  s.email = %q{team@openhood.com}
  s.executables = ["sinatra_app"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "README.md",
     "Rakefile",
     "bin/sinatra_app",
     "features/generator.feature",
     "features/support/env.rb",
     "lib/cucumber/rvm.rb",
     "lib/generators/sinatra_app/sinatra_app_generator.rb",
     "lib/generators/sinatra_app/templates/Gemfile.erb",
     "lib/generators/sinatra_app/templates/Rakefile.erb",
     "lib/generators/sinatra_app/templates/app.rb.erb",
     "lib/generators/sinatra_app/templates/config.ru.erb",
     "lib/generators/sinatra_app/templates/config/test.yml.erb",
     "lib/generators/sinatra_app/templates/features/step_definitions/web_steps.rb.erb",
     "lib/generators/sinatra_app/templates/features/support/blueprints.rb.erb",
     "lib/generators/sinatra_app/templates/features/support/env.rb.erb",
     "lib/generators/sinatra_app/templates/features/support/paths.rb.erb",
     "lib/generators/sinatra_app/templates/spec/models/demo_spec.rb.erb",
     "lib/generators/sinatra_app/templates/spec/spec_helper.rb.erb",
     "lib/generators/sinatra_app/templates/spec/support/blueprints.rb.erb",
     "rvm.yml",
     "sinatra_app_gen.gemspec"
  ]
  s.homepage = %q{http://github.com/openhood/sinatra_app_gen}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Creates a new Sinatra / Sequel or MongoMapper / RSpec / Cucumber / Bundler app.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubigen>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0.6.2"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0a"])
      s.add_development_dependency(%q<aruba>, [">= 0.1.6"])
      s.add_development_dependency(%q<bundler>, [">= 0.9.9"])
    else
      s.add_dependency(%q<rubigen>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0.6.2"])
      s.add_dependency(%q<rspec>, [">= 2.0.0a"])
      s.add_dependency(%q<aruba>, [">= 0.1.6"])
      s.add_dependency(%q<bundler>, [">= 0.9.9"])
    end
  else
    s.add_dependency(%q<rubigen>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0.6.2"])
    s.add_dependency(%q<rspec>, [">= 2.0.0a"])
    s.add_dependency(%q<aruba>, [">= 0.1.6"])
    s.add_dependency(%q<bundler>, [">= 0.9.9"])
  end
end

